apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "komodo.fullname" . }}-ferretdb
  labels:
    app: {{ include "komodo.name" . }}
    chart: {{ include "komodo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "komodo.name" . }}
      tier: ferretdb
  template:
    metadata:
      labels:
        app: {{ include "komodo.name" . }}
        tier: ferretdb
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:1
          env:
            - name: FERRETDB_POSTGRESQL_URL
              value: "postgres://{{ .Values.komodo.db.username }}:{{ .Values.komodo.db.password }}@{{ include "komodo.fullname" . }}-postgres:5432/{{ .Values.komodo.db.name }}"
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | default "regcred" }}