apiVersion: v1
kind: Secret
metadata:
  name: komodo-db-secret
type: Opaque
data:
  KOMODO_DB_USERNAME: {{ .Values.db.username | b64enc | quote }}
  KOMODO_DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  KOMODO_PASSKEY: {{ .Values.passkey | b64enc | quote }}
  KOMODO_WEBHOOK_SECRET: {{ .Values.webhook.secret | b64enc | quote }}
  KOMODO_JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}