apiVersion: v1
kind: Service
metadata:
  name: {{ include "komodo-helm-chart.fullname" . }}-postgres
  labels:
    app: {{ include "komodo-helm-chart.name" . }}
    chart: {{ include "komodo-helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "komodo-helm-chart.fullname" . }}-postgres