apiVersion: v1
kind: Service
metadata:
  name: {{ include "komodo-helm-chart.fullname" . }}-periphery
  labels:
    app: {{ include "komodo-helm-chart.name" . }}
    chart: {{ include "komodo-helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8120
      targetPort: 8120
      protocol: TCP
      name: http
  selector:
    app: {{ include "komodo-helm-chart.fullname" . }}
    component: periphery