apiVersion: v1
kind: Service
metadata:
  name: {{ include "komodo.fullname" . }}-core
  labels:
    app: {{ include "komodo.name" . }}
    chart: {{ include "komodo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9120
      targetPort: 9120
      protocol: TCP
      name: http
  selector:
    app: {{ include "komodo.name" . }}
    component: core