# Yazi basic configuration

[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
max_width = 1920
max_height = 1080
cache_dir = ""

[opener]
edit = ["nvim", "vim", "nano"]
image = ["imv"]
video = ["mpv"]
audio = ["mpv"]
pdf = ["zathura"]