---
- name: Install K3s Server Nodes
  hosts: k3s_servers
  become: true
  vars:
    k3s_version: v1.28.6+k3s1
    k3s_server_args: ""
  tasks:
    - name: Install K3s server
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        sh -s - server {{ k3s_server_args }}
      args:
        creates: /usr/local/bin/k3s
    
    - name: Get K3s token
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      when: inventory_hostname == groups['k3s_servers'][0]
    
    - name: Set fact for K3s token
      ansible.builtin.set_fact:
        k3s_token: "{{ k3s_token.content | b64decode | trim }}"
      when: inventory_hostname == groups['k3s_servers'][0]
    
    - name: Share K3s token with other hosts
      ansible.builtin.set_fact:
        k3s_token: "{{ hostvars[groups['k3s_servers'][0]]['k3s_token'] }}"
      when: inventory_hostname != groups['k3s_servers'][0]

- name: Install K3s Agent Nodes
  hosts: k3s_agents
  become: true
  vars:
    k3s_version: v1.28.6+k3s1
    k3s_url: "https://{{ hostvars[groups['k3s_servers'][0]]['ansible_host'] }}:6443"
  tasks:
    - name: Install K3s agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_URL="{{ k3s_url }}" \
        K3S_TOKEN="{{ hostvars[groups['k3s_servers'][0]]['k3s_token'] }}" \
        sh -
      args:
        creates: /usr/local/bin/k3s

- name: Configure local kubectl
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Create kubectl config directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0700'
    
    - name: Fetch kubeconfig from server
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes
      delegate_to: "{{ groups['k3s_servers'][0] }}"
    
    - name: Update server address in kubeconfig
      ansible.builtin.replace:
        path: ~/.kube/config
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ hostvars[groups['k3s_servers'][0]]['ansible_host'] }}:6443"