
- name: Disable swap on K3s nodes
  hosts: k3s_cluster  # This targets all your server and agent nodes
  become: true        # Run with sudo/root privileges
  gather_facts: true  # Gather system information
  
  tasks:
    - name: Check if swap is enabled
      shell: swapon --show
      register: swap_status
      changed_when: false
      failed_when: false
      
    - name: Disable swap immediately
      command: swapoff -a
      when: swap_status.stdout != ""
      
    - name: Comment out swap entries in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)'
        replace: '# \1'
        backup: yes
      
    - name: Ensure swap remains disabled after reboot
      sysctl:
        name: vm.swappiness
        value: '0'
        state: present
        reload: yes
        
    - name: Verify swap is disabled
      shell: free | grep -i swap
      register: swap_free
      changed_when: false
      failed_when: false

    - name: Show swap status
      debug:
        msg: "Swap is now disabled. Current swap usage: {{ swap_free.stdout }}"
        
    - name: Check for and remove existing swap files
      find:
        paths: /
        patterns: "swapfile,*.swap"
        file_type: file
        recurse: no
      register: swap_files
      
    - name: Remove swap files if found
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ swap_files.files }}"
      when: swap_files.files | length > 0