# File: vars/k3s-ha.yml
# Variables for K3s high availability setup

#
# kube-vip configuration
#
# Virtual IP address for the K3s API
vip_address: 192.168.5.100

# Network interface on the server nodes
# Use 'ip addr' on your server to find the correct interface name
vip_interface: eth0

#
# MetalLB configuration
#
# Version of MetalLB to install
metallb_version: v0.14.9

# IP range for MetalLB to assign to LoadBalancer services
# Make sure these IPs are in your LAN subnet but not assigned to other devices
metallb_ip_range: 192.168.5.101-192.168.5.200

#
# Rancher configuration (if installed)
#
# Hostname for Rancher
rancher_hostname: rancher.k3s.home

# Number of Rancher replicas for HA
rancher_replicas: 2

# Admin password for Rancher
rancher_password: bluechocolate