---
# File: cleanup-rancher.yml
# Description: Removes Rancher and related components from the cluster

- name: Clean up Rancher installation
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/rancher.yml
  
  tasks:
    - name: Confirm cleanup
      pause:
        prompt: "This will remove Rancher, cert-manager, and their resources. Type 'yes' to continue"
      register: confirmation
      failed_when: confirmation.user_input != 'yes'

    - name: Uninstall Rancher
      command: helm uninstall rancher -n {{ rancher_namespace }}
      failed_when: false
      register: rancher_uninstall
      changed_when: rancher_uninstall.rc == 0

    - name: Uninstall cert-manager
      command: helm uninstall cert-manager -n cert-manager
      failed_when: false
      register: cert_manager_uninstall
      changed_when: cert_manager_uninstall.rc == 0

    - name: Remove cert-manager CRDs
      command: kubectl delete -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.crds.yaml
      failed_when: false
      changed_when: true

    - name: Delete cattle-system namespace
      command: kubectl delete namespace {{ rancher_namespace }}
      failed_when: false
      changed_when: true

    - name: Delete cert-manager namespace
      command: kubectl delete namespace cert-manager
      failed_when: false
      changed_when: true

    - name: Display cleanup results
      debug:
        msg:
          - "Rancher cleanup complete!"
          - "You may need to manually check for any remaining resources:"
          - "kubectl get all -n {{ rancher_namespace }}"
          - "kubectl get all -n cert-manager"